export const logIn = ()=> ({type:'LOGIN'})
export const logOut = ()=> ({type:'LOGOUT'})
export const emailInput = (val)=> ({type:'EMAILINPUT', payload:val})
export const passwordInput = (val)=> ({type:'PASSWORDINPUT', payload:val})
export const setFlights = (flights)=>({type:'SETFLIGHTS', payload:flights})
export const getNewFlights = (date)=>({type:'GETNEWFLIGHTS', payload:date})
export const addToFavs = ()=>({type:'ADDTOFAVS'})
export const removeFromFavs = ()=>({type:'REMOVEFROMFAVS'})